language: csharp  
sudo: required  
dist: trusty
mono: none  
env:  
  - CLI_VERSION=latest
dotnet: 1.0.0-preview2-003121
addons:  
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
os:  
  - linux
branches:  
  only:
    - 1.0
install:
  - git submodule update --init --recursive
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -s https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
script: 
  - dotnet restore
  - cd ./src/NadekoBot/ && dotnet build -c Release
  - cd ./src/NadekoBot/bin && tar -czvf ./Release.tar.gz Release
deploy:
  provider: releases
  api_key: "a60d2b21fbb1a9a4759ca4676ecc8add868894b8"
  file: "./Release.tar.gz"
  skip_cleanup: true
  on:
    tags: true